In [5]:
import numpy as np

np.random.rand(10).reshape(np.arange(10).reshape(2,5).shape)-0.5

array([[ 2.75661376e-01, -4.89076278e-02,  2.87722149e-01,
        -2.19084166e-01,  2.46749202e-01],
       [-2.14352337e-04,  3.74293348e-01, -4.74663879e-01,
         2.72456999e-01,  4.12023501e-01]])

In [7]:
def add(v):
    v += 1

u = np.arange(10).reshape(5,2)
add(u[3,1])
u

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
np.random.uniform(-1, 1, 1)

array([0.67281002])